const express=require('express'),bcrypt=require('bcryptjs'),cookieSession=require('cookie-session'),QRCode=require('qrcode'),crypto=require('crypto'),path=require('path');
const { createClient } = require('@libsql/client');
const PORT=+process.env.PORT||3000;
if(!process.env.TURSO_DATABASE_URL||!process.env.TURSO_AUTH_TOKEN){console.error('Missing TURSO_DATABASE_URL/TURSO_AUTH_TOKEN');process.exit(1)}
const db=createClient({url:process.env.TURSO_DATABASE_URL,authToken:process.env.TURSO_AUTH_TOKEN});
const exec=async(sql,args=[])=>db.execute({sql,args});
const one=async(sql,args=[])=>{const r=await exec(sql,args);return r.rows[0]||null};
const all=async(sql,args=[])=>{const r=await exec(sql,args);return r.rows};
async function init(){
 await exec(`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);`);
 await exec(`CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,session_date TEXT NOT NULL,title TEXT NOT NULL,created_at INTEGER NOT NULL,active INTEGER NOT NULL DEFAULT 1);`);
 await exec(`CREATE TABLE IF NOT EXISTS races(id TEXT PRIMARY KEY,session_id TEXT NOT NULL,session_date TEXT,session_title TEXT,first_name TEXT NOT NULL,last_name TEXT NOT NULL,class_name TEXT NOT NULL,course TEXT NOT NULL,start_at INTEGER NOT NULL,finish_at INTEGER,updated_at INTEGER NOT NULL);`);
 await exec(`CREATE TABLE IF NOT EXISTS session_participants(id TEXT PRIMARY KEY,session_id TEXT NOT NULL,first_name TEXT NOT NULL,last_name TEXT NOT NULL,class_name TEXT,group_name TEXT,created_at INTEGER NOT NULL);`);
 await exec(`CREATE INDEX IF NOT EXISTS idx_participants_session ON session_participants(session_id);`);
 await exec(`CREATE TABLE IF NOT EXISTS race_positions(id INTEGER PRIMARY KEY AUTOINCREMENT,race_id TEXT NOT NULL,session_id TEXT NOT NULL,lat REAL NOT NULL,lon REAL NOT NULL,accuracy REAL,recorded_at INTEGER NOT NULL);`);
 await exec(`CREATE INDEX IF NOT EXISTS idx_positions_race ON race_positions(race_id,recorded_at);`);
 await exec(`CREATE INDEX IF NOT EXISTS idx_positions_session ON race_positions(session_id,recorded_at);`);
 for(const col of ['session_date TEXT','session_title TEXT','battery_level REAL','battery_charging INTEGER','gps_status TEXT','gps_last_at INTEGER','finish_reason TEXT']){try{await exec(`ALTER TABLE races ADD COLUMN ${col}`)}catch(e){}}
 for(const col of ['max_duration_sec INTEGER','warning_duration_sec INTEGER','geofence_geojson TEXT']){try{await exec(`ALTER TABLE sessions ADD COLUMN ${col}`)}catch(e){}}
 await exec(`CREATE INDEX IF NOT EXISTS idx_races_session ON races(session_id);`);
 const configuredUser=process.env.ADMIN_USER||'enseignant';
 const configuredPassword=process.env.ADMIN_PASSWORD||'ChangezMoi123!';
 const ah=await one('SELECT value FROM settings WHERE key=?',['admin_hash']);
 if(!ah){await exec('INSERT INTO settings(key,value) VALUES(?,?),(?,?)',['admin_user',configuredUser,'admin_hash',bcrypt.hashSync(configuredPassword,12)]);}
 else if(process.env.ADMIN_PASSWORD){await exec('UPDATE settings SET value=? WHERE key=?',[configuredUser,'admin_user']);await exec('UPDATE settings SET value=? WHERE key=?',[bcrypt.hashSync(configuredPassword,12),'admin_hash']);}
}
const get=async(k,d='')=>(await one('SELECT value FROM settings WHERE key=?',[k]))?.value??d;
const clean=(v,n=120)=>String(v??'').trim().slice(0,n), id=()=>crypto.randomBytes(10).toString('hex');
const app=express();app.use(express.json({limit:'200kb'}));
const AUTH_SECRET=process.env.SESSION_SECRET||'change-me-in-render';
const b64=s=>Buffer.from(s).toString('base64url');
const sign=s=>crypto.createHmac('sha256',AUTH_SECRET).update(s).digest('base64url');
const makeToken=()=>{const payload=b64(JSON.stringify({admin:true,exp:Date.now()+8*3600*1000}));return payload+'.'+sign(payload)};
const validToken=t=>{try{const [p,sig]=String(t||'').split('.');if(!p||!sig||sign(p)!==sig)return false;const x=JSON.parse(Buffer.from(p,'base64url').toString());return x.admin===true&&Number(x.exp)>Date.now()}catch(e){return false}};
const authToken=q=>{const h=String(q.headers.authorization||'');return h.startsWith('Bearer ')?h.slice(7):''};
app.use(express.static(path.join(__dirname,'public'),{setHeaders:(res,file)=>{if(file.endsWith('index.html')||file.endsWith('sw.js')){res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0')}}}));
app.get('/health',(q,r)=>r.json({ok:true,version:'V33'}));
app.get('/api/version',(q,r)=>r.json({version:'V33',build:'2026-10-08-gps-renforce'}));
app.get('/api/me',(q,r)=>r.json({admin:validToken(authToken(q))}));
app.post('/api/login',async(q,r)=>{const expectedUser=process.env.ADMIN_USER||'enseignant';const expectedPassword=process.env.ADMIN_PASSWORD||'ChangezMoi123!';const user=clean(q.body.user,80);const password=String(q.body.password||'');if(user!==expectedUser||password!==expectedPassword)return r.status(401).json({error:'Identifiants incorrects'});r.json({ok:true,admin:true,token:makeToken()})});
app.post('/api/logout',(q,r)=>r.json({ok:true}));
const requireAdmin=(q,r,next)=>{if(validToken(authToken(q)))return next();return r.status(401).json({error:'Accès gestionnaire requis'})};
app.get('/api/sessions',requireAdmin,async(q,r)=>{r.setHeader('Cache-Control','no-store');r.json(await all(`SELECT s.id,s.session_date AS date,s.title,s.created_at,s.active,COUNT(r.id) AS race_count,SUM(CASE WHEN r.finish_at IS NULL THEN 1 ELSE 0 END) AS active_count FROM sessions s LEFT JOIN races r ON r.session_id=s.id GROUP BY s.id ORDER BY s.session_date DESC,s.created_at DESC`));});
app.post('/api/sessions',requireAdmin,async(q,r)=>{const date=clean(q.body.date,10),title=clean(q.body.title,120);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!title)return r.status(400).json({error:'Date et nom obligatoires'});await exec('INSERT INTO sessions(id,session_date,title,created_at,active) VALUES(?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET title=excluded.title,active=1',[date,date,title,Date.now()]);r.json({id:date,date,title,max_duration_sec:null,warning_duration_sec:null,geofence_geojson:null})});
app.get('/api/sessions/:id/config',async(q,r)=>{const sid=clean(q.params.id,50);const s=await one('SELECT id,session_date,title,max_duration_sec,warning_duration_sec,geofence_geojson,active FROM sessions WHERE id=? AND (active=1 OR ?=1)',[sid,validToken(authToken(q))?1:0]);if(!s)return r.status(404).json({error:'Séance introuvable'});r.setHeader('Cache-Control','no-store');r.json({session:s})});
app.post('/api/sessions/:id/config',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50);const s=await one('SELECT id FROM sessions WHERE id=?',[sid]);if(!s)return r.status(404).json({error:'Séance introuvable'});let max=q.body?.max_duration_sec==null?null:Math.round(Number(q.body.max_duration_sec));let warn=q.body?.warning_duration_sec==null?null:Math.round(Number(q.body.warning_duration_sec));if(max!=null&&(!Number.isFinite(max)||max<0))return r.status(400).json({error:'Durée maximale invalide'});if(warn!=null&&(!Number.isFinite(warn)||warn<0))return r.status(400).json({error:'Durée d’alerte invalide'});if(max!=null&&warn!=null&&warn>max)return r.status(400).json({error:'L’alerte préalable doit être inférieure à la durée maximale'});let geo=null;if(q.body?.geofence_geojson){try{const g=typeof q.body.geofence_geojson==='string'?JSON.parse(q.body.geofence_geojson):q.body.geofence_geojson;if(g?.type!=='Polygon'||!Array.isArray(g.coordinates)||!Array.isArray(g.coordinates[0])||g.coordinates[0].length<4)throw new Error();geo=JSON.stringify(g)}catch(e){return r.status(400).json({error:'Zone géographique invalide'})}}await exec('UPDATE sessions SET max_duration_sec=?,warning_duration_sec=?,geofence_geojson=? WHERE id=?',[max,warn,geo,sid]);r.json({ok:true,session:await one('SELECT id,session_date,title,max_duration_sec,warning_duration_sec,geofence_geojson FROM sessions WHERE id=?',[sid])})});
app.get('/api/sessions/:id/results',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50),s=await one('SELECT * FROM sessions WHERE id=?',[sid]);if(!s)return r.status(404).json({error:'Séance introuvable'});r.json({session:s,results:await all('SELECT * FROM races WHERE session_id=? ORDER BY start_at',[sid])})});
app.delete('/api/sessions/:id/results',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50),s=await one('SELECT * FROM sessions WHERE id=?',[sid]);if(!s)return r.status(404).json({error:'Séance introuvable'});const before=await one('SELECT COUNT(*) AS n FROM races WHERE session_id=?',[sid]);await exec('DELETE FROM race_positions WHERE session_id=?',[sid]);await exec('DELETE FROM races WHERE session_id=?',[sid]);const deleted=Number(before?.n||0);r.json({ok:true,deleted:true,count:deleted,session_id:sid});});
app.post('/api/sessions/:id/clear-results',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50),s=await one('SELECT * FROM sessions WHERE id=?',[sid]);if(!s)return r.status(404).json({error:'Séance introuvable'});const before=await one('SELECT COUNT(*) AS n FROM races WHERE session_id=?',[sid]);await exec('DELETE FROM race_positions WHERE session_id=?',[sid]);await exec('DELETE FROM races WHERE session_id=?',[sid]);r.json({ok:true,deleted:true,count:Number(before?.n||0),session_id:sid});});
app.get('/api/sessions/:id/participants',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50);const s=await one('SELECT id FROM sessions WHERE id=?',[sid]);if(!s)return r.status(404).json({error:'Séance introuvable'});r.setHeader('Cache-Control','no-store');r.json({participants:await all('SELECT * FROM session_participants WHERE session_id=? ORDER BY last_name,first_name',[sid])});});
app.post('/api/sessions/:id/participants/import',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50);const s=await one('SELECT id FROM sessions WHERE id=?',[sid]);if(!s)return r.status(404).json({error:'Séance introuvable'});const rows=Array.isArray(q.body?.participants)?q.body.participants:[];if(!rows.length)return r.status(400).json({error:'Aucun participant à importer'});let n=0;for(const x of rows){const first=clean(x.first_name,80),last=clean(x.last_name,80),cls=clean(x.class_name,80),grp=clean(x.group_name,80);if(!first||!last)continue;const pid=clean(x.id,80)||id();await exec('INSERT INTO session_participants(id,session_id,first_name,last_name,class_name,group_name,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET first_name=excluded.first_name,last_name=excluded.last_name,class_name=excluded.class_name,group_name=excluded.group_name',[pid,sid,first,last,cls,grp,Date.now()]);n++;}r.json({ok:true,count:n,participants:await all('SELECT * FROM session_participants WHERE session_id=? ORDER BY last_name,first_name',[sid])});});
app.delete('/api/sessions/:id/participants',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50);await exec('DELETE FROM session_participants WHERE session_id=?',[sid]);r.json({ok:true});});
app.get('/api/sessions/:id/summary',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50);const s=await one('SELECT * FROM sessions WHERE id=?',[sid]);if(!s)return r.status(404).json({error:'Séance introuvable'});const c=await one('SELECT COUNT(*) AS n FROM races WHERE session_id=?',[sid]);const p=await one('SELECT COUNT(*) AS n FROM session_participants WHERE session_id=?',[sid]);const a=await one('SELECT COUNT(*) AS n FROM races WHERE session_id=? AND finish_at IS NULL',[sid]);r.json({session:s,summary:{races:Number(c?.n||0),participants:Number(p?.n||0),active:Number(a?.n||0)}})});
app.delete('/api/sessions/:id',requireAdmin,async(q,r)=>{
 const sid=clean(q.params.id,50);
 const s=await one('SELECT * FROM sessions WHERE id=?',[sid]);
 if(!s)return r.status(404).json({error:'Séance introuvable'});
 const active=await one('SELECT COUNT(*) AS n FROM races WHERE session_id=? AND finish_at IS NULL',[sid]);
 if(Number(active?.n||0)>0)return r.status(409).json({error:'Impossible de supprimer une séance avec un parcours en cours'});
 await exec('DELETE FROM race_positions WHERE session_id=?',[sid]);
 await exec('DELETE FROM races WHERE session_id=?',[sid]);
 await exec('DELETE FROM session_participants WHERE session_id=?',[sid]);
 await exec('DELETE FROM sessions WHERE id=?',[sid]);
 r.json({ok:true,id:sid});
});
app.post('/api/sessions/:id/archive',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50);const s=await one('SELECT * FROM sessions WHERE id=?',[sid]);if(!s)return r.status(404).json({error:'Séance introuvable'});if((await one('SELECT COUNT(*) AS n FROM races WHERE session_id=? AND finish_at IS NULL',[sid]))?.n)return r.status(409).json({error:'Impossible d’archiver une séance avec un parcours en cours'});await exec('UPDATE sessions SET active=0 WHERE id=?',[sid]);r.json({ok:true,id:sid})});
app.post('/api/sessions/:id/duplicate',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50);const s=await one('SELECT * FROM sessions WHERE id=?',[sid]);if(!s)return r.status(404).json({error:'Séance introuvable'});const date=clean(q.body?.date,10),title=clean(q.body?.title,120)||s.title;if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return r.status(400).json({error:'Nouvelle date invalide'});if(await one('SELECT id FROM sessions WHERE id=?',[date]))return r.status(409).json({error:'Une séance existe déjà à cette date'});const nid=date;await exec('INSERT INTO sessions(id,session_date,title,created_at,active,max_duration_sec,warning_duration_sec,geofence_geojson) VALUES(?,?,?,?,1,?,?,?)',[nid,date,title,Date.now(),s.max_duration_sec||null,s.warning_duration_sec||null,s.geofence_geojson||null]);const people=await all('SELECT first_name,last_name,class_name,group_name FROM session_participants WHERE session_id=?',[sid]);for(const x of people){await exec('INSERT INTO session_participants(id,session_id,first_name,last_name,class_name,group_name,created_at) VALUES(?,?,?,?,?,?,?)',[id(),nid,x.first_name,x.last_name,x.class_name||'',x.group_name||'',Date.now()])}r.json({ok:true,id:nid,date,title})});
app.get('/api/sessions/:id/qr',requireAdmin,async(q,r)=>{try{const s=await one('SELECT * FROM sessions WHERE id=?',[clean(q.params.id,50)]);if(!s)return r.status(404).json({error:'Séance introuvable'});const base=(process.env.PUBLIC_URL||`${q.protocol}://${q.get('host')}`).replace(/\/$/,'');const u=base+'/?date='+encodeURIComponent(s.session_date)+'&title='+encodeURIComponent(s.title||'');const data=await QRCode.toDataURL(u,{width:420,margin:1,errorCorrectionLevel:'M'});r.setHeader('Cache-Control','no-store');r.json({url:u,data})}catch(e){r.status(500).json({error:'Génération du QR impossible'})}});
app.post('/api/sync',async(q,r)=>{const items=Array.isArray(q.body?.results)?q.body.results:[];let n=0,authoritative=[];for(const x of items){const sid=clean(x.session_id,50);let ss=await one('SELECT id FROM sessions WHERE id=? AND active=1',[sid]);if(!ss && /^\d{4}-\d{2}-\d{2}$/.test(sid) && clean(x.session_title,120)){await exec('INSERT INTO sessions(id,session_date,title,created_at,active) VALUES(?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET title=excluded.title,active=1',[sid,clean(x.session_date,10)||sid,clean(x.session_title,120),Date.now()]);ss=await one('SELECT id FROM sessions WHERE id=? AND active=1',[sid]);}if(!ss)continue;const rid=clean(x.id,50);if(!rid||!Number(x.start_at))continue;const ex=await one('SELECT * FROM races WHERE id=?',[rid]);if(!ex){await exec('INSERT INTO races(id,session_id,session_date,session_title,first_name,last_name,class_name,course,start_at,finish_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[rid,sid,clean(x.session_date,10),clean(x.session_title,120),clean(x.first_name,80),clean(x.last_name,80),clean(x.class_name,80),clean(x.course,120),+x.start_at,x.finish_at?+x.finish_at:null,Date.now()]);n++;}else if(ex.finish_at && !x.finish_at){authoritative.push(ex);}else if(!ex.finish_at && Number(x.updated_at||0)>Number(ex.updated_at)){await exec('UPDATE races SET session_date=?,session_title=?,first_name=?,last_name=?,class_name=?,course=?,start_at=?,finish_at=?,updated_at=? WHERE id=?',[clean(x.session_date,10),clean(x.session_title,120),clean(x.first_name,80),clean(x.last_name,80),clean(x.class_name,80),clean(x.course,120),+x.start_at,x.finish_at?+x.finish_at:null,Date.now(),rid]);}}r.json({ok:true,synced:n,authoritative,server_time:Date.now()})});
app.get('/api/races/:id/status',async(q,r)=>{const rid=clean(q.params.id,50);const x=await one('SELECT * FROM races WHERE id=?',[rid]);if(!x)return r.status(404).json({error:'Parcours introuvable'});r.setHeader('Cache-Control','no-store');r.json({race:x,server_time:Date.now()})});
app.post('/api/races/:id/manager-stop',requireAdmin,async(q,r)=>{const rid=clean(q.params.id,50);const x=await one('SELECT * FROM races WHERE id=?',[rid]);if(!x)return r.status(404).json({error:'Parcours introuvable'});if(x.finish_at)return r.json({ok:true,already_finished:true,race:x});const at=Date.now();await exec('UPDATE races SET finish_at=?,finish_reason=?,updated_at=? WHERE id=? AND finish_at IS NULL',[at,'manager',at,rid]);const out=await one('SELECT * FROM races WHERE id=?',[rid]);r.json({ok:true,race:out});});
const qrPayload=x=>{const body=b64(JSON.stringify({id:x.id,session_id:x.session_id,session_date:x.session_date,session_title:x.session_title,first_name:x.first_name,last_name:x.last_name,class_name:x.class_name,course:x.course,start_at:x.start_at,finish_at:x.finish_at,finish_reason:x.finish_reason,updated_at:x.updated_at}));return 'COR3.'+body+'.'+sign(body)};
const decodeRecovery=p=>{try{const a=String(p||'').trim().split('.');if(a.length===3&&a[0]==='COR3'){if(sign(a[1])!==a[2])return null;return JSON.parse(Buffer.from(a[1],'base64url').toString())}if(a.length===2&&(a[0]==='COR1'||a[0]==='COR2'))return JSON.parse(Buffer.from(a[1],'base64').toString());return null}catch(e){return null}};
app.get('/api/qr/:id',async(q,r)=>{const x=await one('SELECT * FROM races WHERE id=?',[clean(q.params.id,50)]);if(!x)return r.status(404).json({error:'Résultat introuvable'});const payload=qrPayload(x);r.json({payload,data:await QRCode.toDataURL(payload,{width:420,margin:1,errorCorrectionLevel:'M'})})});
app.post('/api/recover',requireAdmin,async(q,r)=>{const x=decodeRecovery(q.body?.payload);if(!x||!clean(x.id,50)||!clean(x.session_id,50)||!clean(x.first_name,80)||!clean(x.last_name,80)||!Number(x.start_at))return r.status(400).json({error:'QR de récupération invalide'});let ss=await one('SELECT id FROM sessions WHERE id=? AND active=1',[clean(x.session_id,50)]);if(!ss&&/^\d{4}-\d{2}-\d{2}$/.test(clean(x.session_id,50))&&clean(x.session_title,120)){await exec('INSERT INTO sessions(id,session_date,title,created_at,active) VALUES(?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET title=excluded.title,active=1',[clean(x.session_id,50),clean(x.session_date,10)||clean(x.session_id,50),clean(x.session_title,120),Date.now()]);ss=await one('SELECT id FROM sessions WHERE id=? AND active=1',[clean(x.session_id,50)]);}if(!ss)return r.status(404).json({error:'Séance correspondante introuvable'});const rid=clean(x.id,50),ex=await one('SELECT id FROM races WHERE id=?',[rid]);if(!ex){await exec('INSERT INTO races(id,session_id,session_date,session_title,first_name,last_name,class_name,course,start_at,finish_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[rid,clean(x.session_id,50),clean(x.session_date,10),clean(x.session_title,120),clean(x.first_name,80),clean(x.last_name,80),clean(x.class_name,80),clean(x.course,120),+x.start_at,x.finish_at?+x.finish_at:null,Date.now()]);}else{await exec('UPDATE races SET finish_at=?,finish_reason=?,updated_at=? WHERE id=?',[x.finish_at?+x.finish_at:null,clean(x.finish_reason,30)||null,Date.now(),rid]);}r.json({ok:true,result:await one('SELECT * FROM races WHERE id=?',[rid])})});
app.get('/api/sessions/:id/live',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50);r.setHeader('Cache-Control','no-store');r.json({session:await one('SELECT * FROM sessions WHERE id=?',[sid]),results:await all('SELECT * FROM races WHERE session_id=? ORDER BY start_at',[sid]),server_time:Date.now()})});
app.post('/api/telemetry',async(q,r)=>{const x=q.body||{},rid=clean(x.race_id,50),sid=clean(x.session_id,50);if(!rid||!sid)return r.status(400).json({error:'Course invalide'});const row=await one('SELECT id FROM races WHERE id=? AND session_id=?',[rid,sid]);if(!row)return r.status(404).json({error:'Parcours introuvable'});let battery=x.battery_level==null?null:Number(x.battery_level);if(battery!=null&&(!Number.isFinite(battery)||battery<0||battery>1))battery=null;const charging=x.battery_charging==null?null:(x.battery_charging?1:0);const gps=clean(x.gps_status,30)||null;const at=Number(x.recorded_at)||Date.now();const current=await one('SELECT finish_at FROM races WHERE id=? AND session_id=?',[rid,sid]);if(current?.finish_at)return r.json({ok:true,finished:true});await exec('UPDATE races SET battery_level=?,battery_charging=?,gps_status=?,gps_last_at=?,updated_at=updated_at WHERE id=?',[battery,charging,gps,at,rid]);r.json({ok:true});});
app.post('/api/gps',async(q,r)=>{const x=q.body||{};const rid=clean(x.race_id,50),sid=clean(x.session_id,50);const lat=Number(x.lat),lon=Number(x.lon),accuracy=Number(x.accuracy)||null,recorded=Number(x.recorded_at)||Date.now();if(!rid||!sid||!Number.isFinite(lat)||!Number.isFinite(lon)||lat<-90||lat>90||lon<-180||lon>180)return r.status(400).json({error:'Position GPS invalide'});const raceRow=await one('SELECT id,session_id,finish_at FROM races WHERE id=? AND session_id=?',[rid,sid]);if(!raceRow)return r.status(404).json({error:'Parcours introuvable'});if(raceRow.finish_at)return r.json({ok:true,finished:true});await exec('INSERT INTO race_positions(race_id,session_id,lat,lon,accuracy,recorded_at) VALUES(?,?,?,?,?,?)',[rid,sid,lat,lon,accuracy,recorded]);r.json({ok:true});});
app.get('/api/sessions/:id/gps',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50);r.setHeader('Cache-Control','no-store');const rows=await all('SELECT p.race_id,p.lat,p.lon,p.accuracy,p.recorded_at,r.first_name,r.last_name,r.class_name,r.course,r.start_at,r.finish_at,r.finish_reason,r.battery_level,r.battery_charging,r.gps_status,r.gps_last_at FROM race_positions p JOIN races r ON r.id=p.race_id WHERE p.session_id=? ORDER BY p.recorded_at',[sid]);const grouped={};for(const x of rows){(grouped[x.race_id]??=[]).push(x)}r.json({session_id:sid,tracks:grouped,server_time:Date.now()});});
app.get('/api/export/:id',requireAdmin,async(q,r)=>{const s=await one('SELECT * FROM sessions WHERE id=?',[clean(q.params.id,50)]);if(!s)return r.status(404).end();const rows=await all('SELECT * FROM races WHERE session_id=? ORDER BY start_at',[s.id]),clock=x=>x?new Date(Number(x)).toLocaleTimeString('fr-FR'):'';const dur=x=>x?new Date(Number(x)).toISOString().slice(11,19):'',esc=x=>`"${String(x??'').replaceAll('"','""')}"`;const csv=[['Prénom','Nom','Classe','Circuit / balises','Départ','Arrivée','Temps'].map(esc).join(';'),...rows.map(x=>[x.first_name,x.last_name,x.class_name,x.course,clock(x.start_at),clock(x.finish_at),x.finish_at?dur(Number(x.finish_at)-Number(x.start_at)): ''].map(esc).join(';'))].join('\r\n');r.setHeader('Content-Type','text/csv;charset=utf-8');r.setHeader('Content-Disposition',`attachment; filename="orientation-${s.session_date}.csv"`);r.send('\ufeff'+csv)});
init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('Course orientation Render ready on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
