const express=require('express'),bcrypt=require('bcryptjs'),cookieSession=require('cookie-session'),QRCode=require('qrcode'),crypto=require('crypto'),path=require('path');
const { createClient } = require('@libsql/client');
const PORT=+process.env.PORT||3000;
if(!process.env.TURSO_DATABASE_URL||!process.env.TURSO_AUTH_TOKEN){console.error('Missing TURSO_DATABASE_URL/TURSO_AUTH_TOKEN');process.exit(1)}
const db=createClient({url:process.env.TURSO_DATABASE_URL,authToken:process.env.TURSO_AUTH_TOKEN});
const exec=async(sql,args=[])=>db.execute({sql,args});
const one=async(sql,args=[])=>{const r=await exec(sql,args);return r.rows[0]||null};
const all=async(sql,args=[])=>{const r=await exec(sql,args);return r.rows};
async function init(){
 await exec(`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);`);
 await exec(`CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,session_date TEXT NOT NULL,title TEXT NOT NULL,created_at INTEGER NOT NULL,active INTEGER NOT NULL DEFAULT 1);`);
 await exec(`CREATE TABLE IF NOT EXISTS races(id TEXT PRIMARY KEY,session_id TEXT NOT NULL,session_date TEXT,session_title TEXT,first_name TEXT NOT NULL,last_name TEXT NOT NULL,class_name TEXT NOT NULL,course TEXT NOT NULL,start_at INTEGER NOT NULL,finish_at INTEGER,updated_at INTEGER NOT NULL);`);
 for(const col of ['session_date TEXT','session_title TEXT']){try{await exec(`ALTER TABLE races ADD COLUMN ${col}`)}catch(e){}}
 await exec(`CREATE INDEX IF NOT EXISTS idx_races_session ON races(session_id);`);
 const configuredUser=process.env.ADMIN_USER||'enseignant';
 const configuredPassword=process.env.ADMIN_PASSWORD||'ChangezMoi123!';
 const ah=await one('SELECT value FROM settings WHERE key=?',['admin_hash']);
 if(!ah){await exec('INSERT INTO settings(key,value) VALUES(?,?),(?,?)',['admin_user',configuredUser,'admin_hash',bcrypt.hashSync(configuredPassword,12)]);}
 else if(process.env.ADMIN_PASSWORD){await exec('UPDATE settings SET value=? WHERE key=?',[configuredUser,'admin_user']);await exec('UPDATE settings SET value=? WHERE key=?',[bcrypt.hashSync(configuredPassword,12),'admin_hash']);}
}
const get=async(k,d='')=>(await one('SELECT value FROM settings WHERE key=?',[k]))?.value??d;
const clean=(v,n=120)=>String(v??'').trim().slice(0,n), id=()=>crypto.randomBytes(10).toString('hex');
const app=express();app.use(express.json({limit:'200kb'}));app.use(cookieSession({name:'co_admin',keys:[process.env.SESSION_SECRET||'change-me-in-render'],httpOnly:true,sameSite:'lax',secure:true,maxAge:8*3600*1000}));app.use(express.static(path.join(__dirname,'public'),{setHeaders:(res,file)=>{if(file.endsWith('index.html')||file.endsWith('sw.js')){res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0')}}}));
app.get('/health',(q,r)=>r.json({ok:true,version:'V17'}));
app.get('/api/version',(q,r)=>r.json({version:'V17',build:'2026-10-03'}));
app.get('/api/me',(q,r)=>r.json({admin:!!q.session?.admin}));
app.post('/api/login',async(q,r)=>{const expectedUser=process.env.ADMIN_USER||'enseignant';const expectedPassword=process.env.ADMIN_PASSWORD||'ChangezMoi123!';const user=clean(q.body.user,80);const password=String(q.body.password||'');if(user!==expectedUser||password!==expectedPassword)return r.status(401).json({error:'Identifiants incorrects'});q.session.admin=true;r.json({ok:true})});
app.post('/api/logout',(q,r)=>{q.session=null;r.json({ok:true})});
const requireAdmin=(q,r,next)=>{if(q.session?.admin)return next();return r.status(401).json({error:'Accès gestionnaire requis'})};
app.get('/api/sessions',requireAdmin,async(q,r)=>r.json(await all('SELECT id,session_date AS date,title FROM sessions WHERE active=1 ORDER BY session_date DESC')));
app.post('/api/sessions',requireAdmin,async(q,r)=>{const date=clean(q.body.date,10),title=clean(q.body.title,120);if(!/^\\d{4}-\\d{2}-\\d{2}$/.test(date)||!title)return r.status(400).json({error:'Date et nom obligatoires'});await exec('INSERT INTO sessions(id,session_date,title,created_at,active) VALUES(?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET title=excluded.title,active=1',[date,date,title,Date.now()]);r.json({id:date,date,title})});
app.get('/api/sessions/:id/results',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50),s=await one('SELECT * FROM sessions WHERE id=?',[sid]);if(!s)return r.status(404).json({error:'Séance introuvable'});r.json({session:s,results:await all('SELECT * FROM races WHERE session_id=? ORDER BY start_at',[sid])})});
app.delete('/api/sessions/:id/results',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50),s=await one('SELECT * FROM sessions WHERE id=?',[sid]);if(!s)return r.status(404).json({error:'Séance introuvable'});const before=await one('SELECT COUNT(*) AS n FROM races WHERE session_id=?',[sid]);await exec('DELETE FROM races WHERE session_id=?',[sid]);const deleted=Number(before?.n||0);r.json({ok:true,deleted:true,count:deleted,session_id:sid});});
app.post('/api/sessions/:id/clear-results',requireAdmin,async(q,r)=>{const sid=clean(q.params.id,50),s=await one('SELECT * FROM sessions WHERE id=?',[sid]);if(!s)return r.status(404).json({error:'Séance introuvable'});const before=await one('SELECT COUNT(*) AS n FROM races WHERE session_id=?',[sid]);await exec('DELETE FROM races WHERE session_id=?',[sid]);r.json({ok:true,deleted:true,count:Number(before?.n||0),session_id:sid});});
app.get('/api/sessions/:id/qr',requireAdmin,async(q,r)=>{const s=await one('SELECT * FROM sessions WHERE id=?',[clean(q.params.id,50)]);if(!s)return r.status(404).json({error:'Séance introuvable'});const base=(process.env.PUBLIC_URL||`${q.protocol}://${q.get('host')}`).replace(/\/$/,'');const u=base+'/?date='+encodeURIComponent(s.session_date)+'&title='+encodeURIComponent(s.title||'');r.json({url:u,data:await QRCode.toDataURL(u,{width:360,margin:1})})});
app.post('/api/sync',async(q,r)=>{const items=Array.isArray(q.body?.results)?q.body.results:[];let n=0;for(const x of items){const sid=clean(x.session_id,50);let s=await one('SELECT id FROM sessions WHERE id=? AND active=1',[sid]);if(!s && /^\d{4}-\d{2}-\d{2}$/.test(sid) && clean(x.session_title,120)){await exec('INSERT INTO sessions(id,session_date,title,created_at,active) VALUES(?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET title=excluded.title,active=1',[sid,clean(x.session_date,10)||sid,clean(x.session_title,120),Date.now()]);s=await one('SELECT id FROM sessions WHERE id=? AND active=1',[sid]);}if(!s)continue;const rid=clean(x.id,50),ex=await one('SELECT id,updated_at FROM races WHERE id=?',[rid]);if(!ex){await exec('INSERT INTO races(id,session_id,session_date,session_title,first_name,last_name,class_name,course,start_at,finish_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[rid,sid,clean(x.session_date,10),clean(x.session_title,120),clean(x.first_name,80),clean(x.last_name,80),clean(x.class_name,80),clean(x.course,120),+x.start_at,x.finish_at?+x.finish_at:null,Date.now()]);n++;}else if(Number(x.updated_at||0)>Number(ex.updated_at)){await exec('UPDATE races SET session_date=?,session_title=?,finish_at=?,updated_at=? WHERE id=?',[clean(x.session_date,10),clean(x.session_title,120),x.finish_at?+x.finish_at:null,Date.now(),rid]);}}r.json({ok:true,synced:n,server_time:Date.now()})});
app.get('/api/qr/:id',async(q,r)=>{const x=await one('SELECT * FROM races WHERE id=?',[clean(q.params.id,50)]);if(!x)return r.status(404).json({error:'Résultat introuvable'});r.json({data:await QRCode.toDataURL('COR1.'+Buffer.from(JSON.stringify(x)).toString('base64'),{width:420,margin:1})})});
app.get('/api/export/:id',requireAdmin,async(q,r)=>{const s=await one('SELECT * FROM sessions WHERE id=?',[clean(q.params.id,50)]);if(!s)return r.status(404).end();const rows=await all('SELECT * FROM races WHERE session_id=? ORDER BY start_at',[s.id]),clock=x=>x?new Date(Number(x)).toLocaleTimeString('fr-FR'):'';const dur=x=>x?new Date(Number(x)).toISOString().slice(11,19):'',esc=x=>`"${String(x??'').replaceAll('"','""')}"`;const csv=[['Prénom','Nom','Classe','Circuit / balises','Départ','Arrivée','Temps'].map(esc).join(';'),...rows.map(x=>[x.first_name,x.last_name,x.class_name,x.course,clock(x.start_at),clock(x.finish_at),x.finish_at?dur(Number(x.finish_at)-Number(x.start_at)): ''].map(esc).join(';'))].join('\r\n');r.setHeader('Content-Type','text/csv;charset=utf-8');r.setHeader('Content-Disposition',`attachment; filename="orientation-${s.session_date}.csv"`);r.send('\ufeff'+csv)});
init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('Course orientation Render ready on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
